### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by 0Hughman0** [0Hughman0/Cassini#92]
Project needs a logo.

I was thinking something like a conical flask maybe with a `>_` input prompt or something in it. idk

**Comment by exrol** [comment]
Hi !

I made you a logo, feel free to give me feedback :-)

Ciao !

Pull request https://github.com/MrPiada/GoModoro/pull/4

**Comment by exrol** [comment]
https://github.com/0Hughman0/Cassini/pull/93

Hi, here is a first contribution, feel free to give some feed back

Bye !

**Comment by exrol** [comment]
Added a variation, I hope you'll like it
